[build]
  command = "tsc && vite build"
  publish = "dist"
  functions = "netlify/functions-build"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
